workflow:
   rules:
    - if: $CI_COMMIT_BRANCH == "main"

build:
  stage: build
  script:
    - docker build -t furni-decor-api:$CI_COMMIT_SHORT_SHA .

deploy:
  stage: deploy
  script:
    - echo "This is commit sha: $CI_COMMIT_SHORT_SHA"
    - cd /home/gitlab-runner/furnidecor && bash deploy.sh --backend --backend-tag "$CI_COMMIT_SHORT_SHA"
