import { QueryRunner } from 'typeorm';
import { ProductEntity } from 'src/modules/products/entities/product.entity';
import { ProductVariantEntity } from 'src/modules/product-variants/entities/product-variant.entity';
import { ImageEntity } from 'src/modules/image/entities/image.entity';
import slugify from 'slugify';

export const seedSingleProduct = async (queryRunner: QueryRunner) => {
  console.log('🛋️ Running Single Product Seeder');

  // Check if already seeded
  const existing = await queryRunner.manager.find(ProductEntity, {
    where: { name: 'Sleek Concrete Ball' },
  });
  if (existing.length > 0) {
    console.log('⚠️ Product already seeded, skipping...');
    return;
  }

  // Create product
  const productdata = [
    {
      name: 'Sleek Concrete Ball',
      tag: 'Rustic Rubber Sausages',
      description:
        "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
      categoryId: 1,
      quantity: 50,
      dimensions: {
        height: 80,
        width: 120,
        depth: 75,
        seatHeight: 45,
        weight: 25,
      },
      modelNumber: 'XYZ123',
      secondaryMaterial: 'Wood, Metal',
      configuration: '2-seater, L-shape',
      price: 100.5,
      upholsteryMaterial: 'Leather',
      upholsteryColor: 'Brown',
      fillingMaterial: 'Foam',
      finishType: 'Matte',
      adjustableHeadrest: true,
      maxLoad: 120,
      salesPackage: 'Premium packaging with assembly guide',
      originOfManufacture: 'Italy',
      discountValue: 150,
      discountStartDate: new Date('2024-01-01T00:00:00Z'),
      discountEndDate: new Date('2024-12-31T23:59:59Z'),
      warrantySummary: '2 years manufacturer warranty',
      warrantyServiceType: 'On-site service',
      coveredInWarranty: 'Manufacturing defects, material quality issues',
      notCoveredInWarranty: 'Normal wear and tear, accidental damage',
      domesticWarranty: '2 years domestic warranty',
      slug: 'sleek-concrete-ball',
      mainImageId: 4,
      images: [{ id: 1 }, { id: 2 }, { id: 3 }],
    },
    {
      name: 'Modern Velvet Cloud',
      tag: 'Luxury Comfort Series',
      description:
        'Experience ultimate comfort with our premium velvet cloud sofa designed for modern living spaces',
      categoryId: 2,
      quantity: 35,
      dimensions: {
        height: 85,
        width: 200,
        depth: 95,
        seatHeight: 48,
        weight: 45,
      },
      modelNumber: 'CLD456',
      secondaryMaterial: 'Stainless Steel, Wood',
      configuration: '3-seater, U-shape',
      price: 899.99,
      upholsteryMaterial: 'Velvet',
      upholsteryColor: 'Navy Blue',
      fillingMaterial: 'Memory Foam',
      finishType: 'Glossy',
      adjustableHeadrest: false,
      maxLoad: 250,
      salesPackage: 'Flat-pack with tools included',
      originOfManufacture: 'USA',
      discountValue: 100,
      discountStartDate: new Date('2024-02-01T00:00:00Z'),
      discountEndDate: new Date('2024-11-30T23:59:59Z'),
      warrantySummary: '3 years comprehensive warranty',
      warrantyServiceType: 'In-store service',
      coveredInWarranty: 'Frame structure, fabric defects',
      notCoveredInWarranty: 'Stain damage, improper use',
      domesticWarranty: '3 years domestic warranty',
      slug: 'modern-velvet-cloud',
      mainImageId: 8,
      images: [{ id: 7 }, { id: 5 }, { id: 6 }],
    },
    {
      name: 'Oak Wood Heritage',
      tag: 'Classic Collection',
      description:
        'Handcrafted oak wood dining table featuring traditional joinery and elegant design',
      categoryId: 3,
      quantity: 20,
      dimensions: { height: 75, width: 180, depth: 90, weight: 60 },
      modelNumber: 'OAK789',
      secondaryMaterial: 'Glass, Metal',
      configuration: 'Rectangular, Extendable',
      price: 1200.0,
      upholsteryMaterial: 'Wood',
      upholsteryColor: 'Natural Oak',
      fillingMaterial: 'N/A',
      finishType: 'Satin',
      adjustableHeadrest: false,
      maxLoad: 150,
      salesPackage: 'Professional assembly required',
      originOfManufacture: 'Germany',
      discountValue: 200,
      discountStartDate: new Date('2024-03-01T00:00:00Z'),
      discountEndDate: new Date('2024-10-31T23:59:59Z'),
      warrantySummary: '5 years structural warranty',
      warrantyServiceType: 'Manufacturer service',
      coveredInWarranty: 'Wood cracks, structural issues',
      notCoveredInWarranty: 'Surface scratches, water damage',
      domesticWarranty: '5 years domestic warranty',
      slug: 'oak-wood-heritage',
      mainImageId: 12,
      images: [{ id: 11 }, { id: 10 }, { id: 9 }],
    },
    {
      name: 'Minimalist Storage Bed',
      tag: 'Smart Space Solutions',
      description:
        'Space-saving bed frame with integrated storage drawers and modern minimalist design',
      categoryId: 4,
      quantity: 40,
      dimensions: { height: 110, width: 160, depth: 220, weight: 80 },
      modelNumber: 'BED321',
      secondaryMaterial: 'Plywood, Fabric',
      configuration: 'Queen size with storage',
      price: 650.75,
      upholsteryMaterial: 'Fabric',
      upholsteryColor: 'Charcoal Grey',
      fillingMaterial: 'Plywood',
      finishType: 'Matte',
      adjustableHeadrest: true,
      maxLoad: 300,
      salesPackage: 'Complete bed frame with instructions',
      originOfManufacture: 'Sweden',
      discountValue: 75,
      discountStartDate: new Date('2024-04-01T00:00:00Z'),
      discountEndDate: new Date('2024-09-30T23:59:59Z'),
      warrantySummary: '2 years limited warranty',
      warrantyServiceType: 'Online support',
      coveredInWarranty: 'Frame defects, drawer mechanisms',
      notCoveredInWarranty: 'Mattress, personal items',
      domesticWarranty: '2 years domestic warranty',
      slug: 'minimalist-storage-bed',
      mainImageId: 16,
      images: [{ id: 15 }, { id: 14 }, { id: 13 }],
    },
    {
      name: 'Ergonomic Office Chair',
      tag: 'Professional Series',
      description:
        'High-back ergonomic office chair with lumbar support and adjustable features for all-day comfort',
      categoryId: 5,
      quantity: 100,
      dimensions: {
        height: 130,
        width: 68,
        depth: 70,
        seatHeight: 45,
        weight: 25,
      },
      modelNumber: 'ERG555',
      secondaryMaterial: 'Aluminum, Plastic',
      configuration: 'Executive high-back',
      price: 349.99,
      upholsteryMaterial: 'Mesh',
      upholsteryColor: 'Black',
      fillingMaterial: 'High-density Foam',
      finishType: 'Matte',
      adjustableHeadrest: true,
      maxLoad: 150,
      salesPackage: 'Fully assembled',
      originOfManufacture: 'China',
      discountValue: 50,
      discountStartDate: new Date('2024-05-01T00:00:00Z'),
      discountEndDate: new Date('2024-08-31T23:59:59Z'),
      warrantySummary: '1 year comprehensive warranty',
      warrantyServiceType: 'Replacement service',
      coveredInWarranty: 'Mechanism failure, material defects',
      notCoveredInWarranty: 'Normal wear, cosmetic damage',
      domesticWarranty: '1 year domestic warranty',
      slug: 'ergonomic-office-chair',
      mainImageId: 20,
      images: [{ id: 19 }, { id: 18 }, { id: 17 }],
    },
    {
      name: 'Vintage Bookshelf',
      tag: 'Retro Collection',
      description:
        'Inspired by mid-century design, this bookshelf combines functionality with timeless aesthetic appeal',
      categoryId: 6,
      quantity: 25,
      dimensions: { height: 180, width: 120, depth: 35, weight: 40 },
      modelNumber: 'BKS777',
      secondaryMaterial: 'Metal, Glass',
      configuration: '5-shelf vertical',
      price: 425.5,
      upholsteryMaterial: 'Wood',
      upholsteryColor: 'Walnut',
      fillingMaterial: 'N/A',
      finishType: 'Vintage Finish',
      adjustableHeadrest: false,
      maxLoad: 200,
      salesPackage: 'Flat-pack with hardware',
      originOfManufacture: 'Denmark',
      discountValue: 85,
      discountStartDate: new Date('2024-06-01T00:00:00Z'),
      discountEndDate: new Date('2024-12-15T23:59:59Z'),
      warrantySummary: '3 years structural warranty',
      warrantyServiceType: 'Parts replacement',
      coveredInWarranty: 'Shelf brackets, structural integrity',
      notCoveredInWarranty: 'Surface finish, shelf placement',
      domesticWarranty: '3 years domestic warranty',
      slug: 'vintage-bookshelf',
      mainImageId: 28,
      images: [{ id: 27 }, { id: 26 }, { id: 25 }],
    },
    {
      name: 'Outdoor Lounge Set',
      tag: 'Garden Collection',
      description:
        'Weather-resistant outdoor furniture set perfect for patio, garden, or balcony relaxation',
      categoryId: 7,
      quantity: 15,
      dimensions: {
        height: 85,
        width: 180,
        depth: 85,
        seatHeight: 42,
        weight: 35,
      },
      modelNumber: 'OUT888',
      secondaryMaterial: 'Aluminum, Textilene',
      configuration: '3-piece set',
      price: 799.0,
      upholsteryMaterial: 'Synthetic Rattan',
      upholsteryColor: 'Beige',
      fillingMaterial: 'Cushion Foam',
      finishType: 'Weather-resistant',
      adjustableHeadrest: true,
      maxLoad: 120,
      salesPackage: 'Complete set with cushions',
      originOfManufacture: 'Indonesia',
      discountValue: 120,
      discountStartDate: new Date('2024-07-01T00:00:00Z'),
      discountEndDate: new Date('2024-11-15T23:59:59Z'),
      warrantySummary: '2 years weather warranty',
      warrantyServiceType: 'Component replacement',
      coveredInWarranty: 'Frame corrosion, fabric fading',
      notCoveredInWarranty: 'Weather damage, improper storage',
      domesticWarranty: '2 years domestic warranty',
      slug: 'outdoor-lounge-set',
      mainImageId: 24,
      images: [{ id: 21 }, { id: 22 }, { id: 23 }],
    },
    {
      name: 'Kids Bunk Bed',
      tag: 'Children Safety Series',
      description:
        'Safe and fun bunk bed with guard rails and ladder, perfect for siblings or sleepovers',
      categoryId: 8,
      quantity: 30,
      dimensions: { height: 160, width: 140, depth: 200, weight: 75 },
      modelNumber: 'KID999',
      secondaryMaterial: 'Pine Wood, Metal',
      configuration: 'Standard bunk with ladder',
      price: 550.25,
      upholsteryMaterial: 'Wood',
      upholsteryColor: 'White',
      fillingMaterial: 'Solid Wood',
      finishType: 'Non-toxic Paint',
      adjustableHeadrest: false,
      maxLoad: 180,
      salesPackage: 'Full bed assembly required',
      originOfManufacture: 'Canada',
      discountValue: 90,
      discountStartDate: new Date('2024-08-01T00:00:00Z'),
      discountEndDate: new Date('2024-10-31T23:59:59Z'),
      warrantySummary: '4 years safety warranty',
      warrantyServiceType: 'Technical support',
      coveredInWarranty: 'Structural safety, rail integrity',
      notCoveredInWarranty: 'Mattress, personal modifications',
      domesticWarranty: '4 years domestic warranty',
      slug: 'kids-bunk-bed',
      mainImageId: 28,
      images: [{ id: 25 }, { id: 26 }, { id: 27 }],
    },
    {
      name: 'Executive Desk',
      tag: 'Professional Workspace',
      description:
        'Spacious executive desk with cable management and premium build quality for home office',
      categoryId: 9,
      quantity: 45,
      dimensions: { height: 75, width: 160, depth: 80, weight: 55 },
      modelNumber: 'DSK111',
      secondaryMaterial: 'Steel, Glass',
      configuration: 'L-shaped executive',
      price: 675.8,
      upholsteryMaterial: 'Wood Veneer',
      upholsteryColor: 'Espresso',
      fillingMaterial: 'Particle Board',
      finishType: 'High Gloss',
      adjustableHeadrest: false,
      maxLoad: 100,
      salesPackage: 'Desk top and legs separate',
      originOfManufacture: 'Malaysia',
      discountValue: 110,
      discountStartDate: new Date('2024-09-01T00:00:00Z'),
      discountEndDate: new Date('2024-12-24T23:59:59Z'),
      warrantySummary: '3 years desk warranty',
      warrantyServiceType: 'Parts delivery',
      coveredInWarranty: 'Desktop surface, leg stability',
      notCoveredInWarranty: 'Surface scratches, accessory damage',
      domesticWarranty: '3 years domestic warranty',
      slug: 'executive-desk',
      mainImageId: 32,
      images: [{ id: 21 }, { id: 29 }, { id: 30 }],
    },
    {
      name: 'Accent Armchair',
      tag: 'Designer Collection',
      description:
        'Statement armchair with unique geometric design, perfect for adding character to any room',
      categoryId: 10,
      quantity: 28,
      dimensions: {
        height: 95,
        width: 85,
        depth: 90,
        seatHeight: 46,
        weight: 28,
      },
      modelNumber: 'ACC222',
      secondaryMaterial: 'Wood, Foam',
      configuration: 'Single armchair',
      price: 299.99,
      upholsteryMaterial: 'Velvet',
      upholsteryColor: 'Emerald Green',
      fillingMaterial: 'High-resilience Foam',
      finishType: 'Textured',
      adjustableHeadrest: false,
      maxLoad: 130,
      salesPackage: 'Ready to use',
      originOfManufacture: 'UK',
      discountValue: 60,
      discountStartDate: new Date('2024-10-01T00:00:00Z'),
      discountEndDate: new Date('2024-12-20T23:59:59Z'),
      warrantySummary: '2 years fabric warranty',
      warrantyServiceType: 'In-home service',
      coveredInWarranty: 'Fabric defects, frame structure',
      notCoveredInWarranty: 'Stain removal, color fading',
      domesticWarranty: '2 years domestic warranty',
      slug: 'accent-armchair',
      mainImageId: 36,
      images: [{ id: 35 }, { id: 33 }, { id: 34 }],
    },
  ];

  // Create variants
  //   const variants: ProductVariantEntity[] = [
  //     {
  //       productId: product.id,
  //       product,
  //       colorId: 1,
  //       image: { id: 4 } as ImageEntity,
  //       wishlists: [],
  //     } as ProductVariantEntity,
  //     {
  //       productId: product.id,
  //       product,
  //       colorId: 3,
  //       image: { id: 5 } as ImageEntity,
  //       wishlists: [],
  //     } as ProductVariantEntity,
  //   ];

  //   product.variants = variants;
  const products = productdata.map((prod) =>
    queryRunner.manager.create(ProductEntity, { ...prod }),
  );
  // Save product (with variants and images)
  await queryRunner.manager.save(ProductEntity, products);

  console.log('✅ Single product seeded successfully!');
};
