export enum SERIALIZATION_GROUP {
  ADMIN = 'ADMIN',
  PUBLIC_USER = 'PUBLIC_USER',
  SYSTEM_USER = 'SYSTEM_USER',
  PARTNERS = 'PARTNERS',
}

export const DELETE_AT_FIELD_GROUP = ['DELETE_AT'];
export const ADMIN_ONLY_GROUP = [SERIALIZATION_GROUP.ADMIN];
export const PUBLIC_USER_ONLY_GROUP = [SERIALIZATION_GROUP.PUBLIC_USER];
export const SYSTEM_USER_ONLY_GROUP = [SERIALIZATION_GROUP.SYSTEM_USER];
export const PARTNERS_ONLY_GROUP = [SERIALIZATION_GROUP.PARTNERS];

export const ALL_GROUP = [
  SERIALIZATION_GROUP.ADMIN,
  SERIALIZATION_GROUP.PUBLIC_USER,
  SERIALIZATION_GROUP.SYSTEM_USER,
];
